appname: Open Platform

server:
  host: 127.0.0.1
  hostname: open.hustunique.com
  port: 8000
  secretkey: 12345678

qcloudsms:
  appid: 
  appkey:
  sign:

wework:
  cropid:
  agentid:
  agentsecret: 
  secret: 
  contactsecret:

smtp: 
  sender: XXX@mail.XXX.com
  password: 
  host: smtp.mail.com